version: '3.8'
services:
  ruby:
    build:
      dockerfile: .infra/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
